### ISSUE TITLE
Room state simultaneous synch 

### ISSUE THREAD

**Issue by rohan-wire** [bifurcation/mimi-arch#2]
"At any given time, all of the clients and servers participating in the room have the same view of the room's state."
That's impossible. What do we actually mean?

**Comment by bifurcation** [comment]
It may be a little idealistic, but doesn't seem impossible if you allow for some propagation time.  What I mean is basically that when Alice gets added to a room, all of the clients and servers in the room agree that she's in the room.  Likewise, when she gets band, no server will forward a message from her.

**Comment by rohan-wire** [comment]
Leaving aside for the moment that we don't have a clear idea of what "she's *in* the room" means, I think this is still impossible. What we *can* know is if we are in sync with a specific event, epoch, timestamp or hash from the hub.
