### ISSUE TITLE
e2e security state cannot be not "room state"

### ISSUE THREAD

**Issue by rohan-wire** [bifurcation/mimi-arch#3]
These statements are contradictory (my emphasis):

"At any given time, all of the clients **and servers** participating in the room have the same view of the room's state."

"The state of the room includes a few types of information, most importantly:

* The end-to-end security state of the room"

"Messages sent within a room are protected by an end-to-end security protocol to ensure that the servers handling messages cannot inspect or tamper with messages."

**Comment by bifurcation** [comment]
Note that there is a clarification elsewhere that the servers know the **public aspects** of the E2E state (i.e., the ratchet tree).
