### ISSUE TITLE
"control protocols" is not a single cohesive group

### ISSUE THREAD

**Issue by rohan-wire** [bifurcation/mimi-arch#4]
I don't think it is useful to talk about "Control Protocols" as a bucket of things yet. We should be talking the specific things that are listed and then see if there are enough protocol similarities.

**Comment by bifurcation** [comment]
To be clear, I didn't mean to imply that there were any similarities to these protocols aside from (1) using events / transport to pass information around and (2) manipulating group state.  The point is that servers do two things: Forward messages and maintain room state.  "Control protocols" is just a bucket for the latter.
